name: ZenPro - provide secret
on:
  workflow_call:
    outputs:
      zenpro:
        description: 'ZenCreator API key'
        value: ${{ jobs.provide_secret.outputs.zenpro }}

jobs:
  provide_secret:
    runs-on: ubuntu-latest
    outputs:
      zenpro: ${{ steps.set.outputs.zenpro }}
    steps:
      - name: Expose zenpro as workflow output
        id: set
        run: |
          echo "zenpro=${{ secrets.zenpro }}" >> $GITHUB_OUTPUT
